- type: job
  id: ESPhysician
  name: ESjob-name-physician
  description: ESjob-description-physician
  playTimeTracker: ESJobPhysician
  startingGear: ESPhysicianGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-hop
  access:
  - Medical
  - Maintenance
  - Chemistry

- type: startingGear
  id: ESPhysicianGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: MedicalPDA
    gloves: ClothingHandsGlovesColorBlue
    head: ClothingHeadHatSurgcapBlue
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    outerClothing: ClothingOuterCoatLabOpened
    back: ClothingBackpackMedical
  storage:
    back:
    - ESBoxSurvivalMedical

- type: chameleonOutfit
  id: ESPhysician
  job: ESPhysician
  hidden: false
